/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finalproject;

import finalproject.client.clientapi.ClientApi;
import finalproject.client.clientapi.ClientApiFactory;
import finalproject.vcs.command.request.RequestCommand;

public class App {
    public static void main(String[] args) {
        ClientApi client = ClientApiFactory.getCli();
        RequestCommand command = client.getCommand();
    }
}
